### ISSUE TITLE
phpQuery missing from composer.json

### ISSUE THREAD

**Issue by axis80** [madoublet/respond6#8]
I pulled down the latest and got this error when I tried to edit a page:

Class 'phpQuery' not found

Entering this command fixed it:

composer require electrolinux/phpquery

I think you will need to do that to add that package to composer.json

**Comment by madoublet** [comment]
I am in the process of removing phpQuery in favor of simple_html_dom as the latter provides a few more useful attribute functions and also is much less destructive to the format of the document.  I am guessing there is a reference to phpQuery still hanging around causing the error.  Are you getting a specific line/file with that error?

**Comment by axis80** [comment]
/app/Http/Controllers/EditController.php on line 53

I did a search through the codebase for the 'phpQuery' and found that it also appears in the file /app/Respond/Models/Setting.php

**Comment by madoublet** [comment]
Thanks!  I will update this in the next push.

**Comment by madoublet** [comment]
This should be fixed in the latest update.
