### ISSUE TITLE
How to install hashedit?

### ISSUE THREAD

**Issue by axis80** [madoublet/respond6#9]
I hate to bug you for support since I know you have your hands full with development, but I'm pretty stuck.

Everything seems to be working correctly on my Respond6 installation except for the page editor.  It apparently has something to do with hashedit being out of sync with the main project.

The hashedit package that is installed via npm is apparently an older version which is missing the i18n file.  

Additionally, all of my npm modules get installed into /node_modules, whereas the app is apparently expecting them to be in /public/node_modules.  I'm not sure whether I have some paths defined incorrectly in Apache.  In the meantime, I have just been running "npm install" and then copying the node_modules folder into /public/node_modules.

I tried wiping out the /public/node_modules/hashedit folder and pulling down the latest hashedit directly from Github.  (There is only a master branch so that's the one I tried.)  That adds the i18n file that was missing, but now it throws this error when I load the page editor:

Uncaught SyntaxError: Unexpected identifier on edit:183

The offending line is the one that starts with "sortable".  

hashedit.setup({
  url: 'derrick4/page/about.html'
  sortable: '.col, .column',
  login: '/login/derrick4'
  translate: true,
  languagePath: '/i18n/{{language}}.json',
  auth: 'token',
  authHeader: 'X-AUTH'
});

Is the Github hashedit repo the latest code?  Any advice on how to install it for use within Respond?  For starters... what folder should hashedit go into?

**Comment by madoublet** [comment]
I need to release a new version of the editor to NPM prior to the beta.  But, you can easily work around this.  Create a folder at public/dev/hashedit.  Pull the hashedit repository into that folder and then set APP_ENV to _development_ in your .env file.

**Comment by madoublet** [comment]
I bumped the version of Hashedit to 0.5.9 on npm.  So, this should fix your problem.

**Comment by axis80** [comment]
I was not able to get it working with the npm version of hashedit, but your instructions for changing APP_ENV worked.  

So, I now have R6 up and running completely.

Thanks again for your help.

**Comment by madoublet** [comment]
I will have to test the production setup and see what is going on there.
